### ISSUE TITLE
Question: How TestFlight beta releases are published? I have V1.11.3 (1551) build via TestFlight but AppStore has V1.11.4 official release already?

### ISSUE THREAD

**Issue by mika-n** [AndrewBennet/ReadingList#32]
Hi,

I have been using ReadingList app for a while and I'm very happy with it. But, I have a question about AppStore's testFlight beta releases.

Today I realized that my TestFligt beta release of the app will expire in a month. The beta app seems to be V1.11.3 (1551) build, but I realized that the official version in AppStore is newer version build (V1.11.4).

Are TestFlight beta releases published only every now and then or do you plan to release test flight releases few weeks before an official build?

If and When I would install the official version from AppStore then I guess it would automatically re-use the book list from the test flight version and the database format is migrated if there are changes?

Please don't hesitate to release testflight builds, because I'd be happy to help you to test new features. I understand that something may break in beta builds, after all I'm a software developer also so I know how it sometimes go and i'm ready to take the risk :-)

**Comment by AndrewBennet** [comment]
The TestFlight builds are released on a rather ad-hoc basis. Anything pushed to master gets automatically built and uploaded, but I only publish them to the public beta once I'm reasonably sure that it's not going to lose data, or be riddled with major bugs!

If you install the AppStore build, it will replace the TestFlight install and use the same data. The only restriction is you can't always go backwards in versions. So if you installed a hypothetical v2.0 from TestFlight, and then installed v1.9 from the App Store, you'd probably hit a problem. However, the app would give you a popup at that point to explain what the issue is. You could then reinstall v2.0 from TestFlight again to revert back to where you were.

If you want, I can add your email to the "internal testers" group so you'll get access to all builds?

I will also soon publish a beta of the upcoming next version. I've not had as much time recently to finish off the next release, so it's taking a little while... should be soon though!

**Comment by mika-n** [comment]
Okey. Thanks for the explanation. I'd would be happy to get an access to all builds (for example, from github commits I can see that subtitle support seems to be there ready to be tested).
