### ISSUE TITLE
Is the project still active?

### ISSUE THREAD

**Issue by fedemengo** [AndrewBennet/ReadingList#64]
Hey there, I recently discovered the app, I was really interesting in buying the pro version. I was just wondering if the project is still active

**Comment by AndrewBennet** [comment]
Hi there,

Yes, the project is active. However, since I created the paid component (Pro), I've forked the repository to a non-public version to continue the work. This repository I left public for posterity; this is the last released v1 version, the current version in the app store is v2.

Hope that helps,
Andrew

**Comment by wafflecoffee** [comment]
Is that even allowed? With the GPL-3.0 license, if something under the GPL is distributed, the source must also be distributed freely. Unless the v2 code is completely independent from the v1 code, you're in violation of your own license.

**Comment by AndrewBennet** [comment]
Interesting idea. However, as the sole copyright owner, I have rights to the source code which go beyond what is conferred by the GPL licence, so I am free to use it as I wish. I do agree that I can't revoke the GPL licence for what has already been published though.
